import AppKit

/// Watches the system pasteboard and records new copies into the history store.
final class ClipboardMonitor {
    private let pb = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    let store: HistoryStore

    // Pasteboard "markers" set by password managers / transient tooling that
    // we deliberately skip (see nspasteboard.org conventions).
    private let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    init(store: HistoryStore) {
        self.store = store
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        let t = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in self?.tick() }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    /// Call after we write to the pasteboard ourselves so the write isn't
    /// re-ingested as a fresh copy.
    func ignoreCurrentChange() {
        lastChangeCount = pb.changeCount
    }

    private func tick() {
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        let types = Set(pb.types ?? [])
        guard ignoredTypes.isDisjoint(with: types) else { return }

        // 1. Plain text wins when present.
        if let s = pb.string(forType: .string),
           !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            store.addText(s)
            return
        }

        // 2. Images: decode to a bitmap and re-encode to a canonical PNG so the
        //    same picture copied as PNG vs TIFF de-duplicates to one entry.
        if let data = pb.data(forType: .png) ?? pb.data(forType: .tiff),
           let rep = NSBitmapImageRep(data: data),
           let png = rep.representation(using: .png, properties: [:]) {
            store.addImage(pngData: png)
            return
        }

        // 3. Copied files -> record their paths as a text entry.
        if let urls = pb.readObjects(forClasses: [NSURL.self],
                                     options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            store.addText(urls.map { $0.path }.joined(separator: "\n"))
        }
    }
}
